#Steronik nawadniania, dopisać piny gpio przekaźnika, dodać led przez rezystor 1.1k 2W do pinu przekaźnika, zastosować włączniki chwilowe, do zmiany stanu przekaźnika.


esphome:
  name: sterownik_nawadniania
  friendly_name: Sterownik Nawadniania

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret enc_key

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Nawadnianie AP"
    password: "XXXxxxXXX"

captive_portal:

# 8 przekaźników (zaworów)
switch:
  - platform: gpio
    name: "Zawór 1"
    pin: GPIO13
    id: valve1
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Zawór 2"
    pin: GPIO12
    id: valve2
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Zawór 3"
    pin: GPIO14
    id: valve3
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Zawór 4"
    pin: GPIO27
    id: valve4
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Zawór 5"
    pin: GPIO26
    id: valve5
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Zawór 6"
    pin: GPIO25
    id: valve6
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Zawór 7"
    pin: GPIO33
    id: valve7
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Zawór 8"
    pin: GPIO32
    id: valve8
    restore_mode: ALWAYS_OFF

# 8 przycisków chwilowych — zmieniają stan zaworu
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Przycisk Zawór 1"
    on_press:
      then:
        - switch.toggle: valve1

  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    name: "Przycisk Zawór 2"
    on_press:
      then:
        - switch.toggle: valve2

  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: true
    name: "Przycisk Zawór 3"
    on_press:
      then:
        - switch.toggle: valve3

  - platform: gpio
    pin:
      number: GPIO17
      mode: INPUT_PULLUP
      inverted: true
    name: "Przycisk Zawór 4"
    on_press:
      then:
        - switch.toggle: valve4

  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: "Przycisk Zawór 5"
    on_press:
      then:
        - switch.toggle: valve5

  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
    name: "Przycisk Zawór 6"
    on_press:
      then:
        - switch.toggle: valve6

  - platform: gpio
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true
    name: "Przycisk Zawór 7"
    on_press:
      then:
        - switch.toggle: valve7

  - platform: gpio
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
      inverted: true
    name: "Przycisk Zawór 8"
    on_press:
      then:
        - switch.toggle: valve8
